name: Development Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APKs
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
      run: ./gradlew assembleDebug

    - name: Upload Universal Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: com.lanrhyme.shardlauncher-all-debug
        path: app/build/outputs/apk/debug/app-universal-debug.apk

    - name: Upload Debug APK (armeabi-v7a)
      uses: actions/upload-artifact@v4
      with:
        name: com.lanrhyme.shardlauncher-armeabi-v7a-debug
        path: app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk

    - name: Upload Debug APK (arm64-v8a)
      uses: actions/upload-artifact@v4
      with:
        name: com.lanrhyme.shardlauncher-arm64-v8a-debug
        path: app/build/outputs/apk/debug/app-arm64-v8a-debug.apk

    - name: Upload Debug APK (x86)
      uses: actions/upload-artifact@v4
      with:
        name: com.lanrhyme.shardlauncher-x86-debug
        path: app/build/outputs/apk/debug/app-x86-debug.apk

    - name: Upload Debug APK (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: com.lanrhyme.shardlauncher-x86_64-debug
        path: app/build/outputs/apk/debug/app-x86_64-debug.apk
