name: Release Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APKs for all ABIs
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
      run: ./gradlew assembleRelease

    - name: List files in APK output directory
      run: ls -R app/build/outputs/apk/release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Universal Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-universal-release.apk
        asset_name: com.lanrhyme.shardlauncher-all.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Release APKs (armeabi-v7a)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk
        asset_name: com.lanrhyme.shardlauncher-armeabi-v7a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Release APKs (arm64-v8a)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-arm64-v8a-release.apk
        asset_name: com.lanrhyme.shardlauncher-arm64-v8a.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Release APKs (x86)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-x86-release.apk
        asset_name: com.lanrhyme.shardlauncher-x86.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload Release APKs (x86_64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-x86_64-release.apk
        asset_name: com.lanrhyme.shardlauncher-x86_64.apk
        asset_content_type: application/vnd.android.package-archive
